const appname = "ShopGuru";
const appversion = "Version 1.0.0";
//const credits = "@zakir";
const email = "Email";
const emailHint = "admin@email.com";
const password = "Password";
const passwordHint = "******";
const retypePassword = "Retype Password";
const name = "Name";
const nameHint = "Your Name";
const forgetPass = "Forget Password";
const login = "Log in";
const signup = "Sign up";
const createNewAccount = "or create a new account";
const loninWith = "Login With";
const privacyPolicy = "Privacy Policy";
const termAndCond = "Terms and Conditions";
const alreadyAccount = "Already have an account? ";
//Home Strings
const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";
//home screen strings
const searchAnything = "Search anything...",
    todayDeal = "Today's Deal",
    flashSale = "Flash Sale",
    topCategories = "Top Categories",
    brands = "Brands",
    topSellers = "Top Sellers",
    featuredProduct = "Featured Product",
    allProduct = "All Products",
    featuredCategories = "Featured Categories",
    womenDresses = "Women Dresses",
    girlWatches = "Girls Watches",
    mobilePhone = "Mobile Phone",
    boysGlasses = "Boys Glasses",
    tShirts = "T-Shirts",
    girlsDresses = "Girls Dresses";
